### ISSUE TITLE
cleanup options

### ISSUE THREAD

**Issue by vdbe** [catppuccin/tmux#275]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

- [ ] Merge `@catppuccin_window_status_enable` and `@catppuccin_window_status_icon_enable`
- [ ] Remove options that don't need to be handled by catppuccin/tmux
- [ ] add list of options to interpolate, this can get rid of options like `@catppuccin_menu_style`
