### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by vdbe** [catppuccin/tmux#276]
- [ ] Move options documentation out of README
- [ ] Separate file for module options?
- [ ] Add FAQ
- [ ] Document installation options and problems including forking, renaming, tags, ...
  - https://github.com/catppuccin/tmux/issues/289#issuecomment-2289218740
- [ ] Update [./assets/overview.png](https://github.com/catppuccin/tmux/blob/main/assets/overview.png)
